import './globals.scss'
import { Roboto } from 'next/font/google'

const roboto = Roboto({ 
  subsets: ['latin'], 
  weight: ['400' , '900']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`${roboto.className} bg-slate-100`}>{children}</body>
    </html>
  )
}
